spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medicure
    username: root
    password: khushi
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  thymeleaf:
    enabled: true
  web:
    resources:
      static-locations: classpath:/static/
